const cards = {
  main: [
    {
      img: "img/1.webp",
      imgHover: "img/1b.webp",
      discount: "-50%",
      eco: "Sostenibile",
      heart: `&hearts;`,
      href: "#",
      brand: "Levi's",
      desc: "relaxed fit tee unisex",
      priceNew: "14,99€",
      priceOld: "29,99€",
    },
    {
      img: "img/2.webp",
      imgHover: "img/2b.webp",
      discount: "-30%",
      eco: "",
      heart: "&hearts;",
      href: "#",
      brand: "Guess",
      desc: "roses tee",
      priceNew: "20,99€",
      priceOld: "29,99€",
    },
    {
      img: "img/3.webp",
      imgHover: "img/3b.webp",
      discount: "-30%",
      eco: "",
      heart: "&hearts;",
      href: "#",
      brand: "Come Zucchero Filato",
      desc: "voglia di colori pastello",
      priceNew: "129,99€",
      priceOld: "184,99€",
    },
    {
      img: "img/4.webp",
      imgHover: "img/4b.webp",
      discount: "-50%",
      eco: "Sostenibile",
      heart: "&hearts;",
      href: "#",
      brand: "Levi's",
      desc: "tee unisex",
      priceNew: "14,99€",
      priceOld: "29,99€",
    },
    {
      img: "img/5.webp",
      imgHover: "img/5b.webp",
      discount: "",
      eco: "",
      heart: "&hearts;",
      href: "#",
      brand: "Maya Deluxe",
      desc: "stripe bodice",
      priceNew: "99,99€",
      priceOld: "",
    },
    {
      img: "img/6.webp",
      imgHover: "img/6b.webp",
      discount: "",
      eco: "Sostenibile",
      heart: "&hearts;",
      href: "#",
      brand: "Come Zucchero Filato",
      desc: "voglia di colori pastello",
      priceNew: "129,99€",
      priceOld: "184,99€",
    },
  ],
};

export { cards };
